spring.application.name=user-service
server.port=8081

spring.jackson.deserialization.fail-on-unknown-properties=true

eureka.client.service-url.defaultZone=${EUREKA_DEFAULTZONE}

auth0.domain=${AUTH0_DOMAIN}
auth0.management.domain=${AUTH0_MANAGMENT_DOMAIN}
auth0.management.client-id=${AUTH0_MANAGMENT_CLIENT_ID}
auth0.management.client-secret=${AUTH0_MANAGMENT_CLIENT_SECRET}
auth0.management.audience=https://${AUTH0_MANAGEMENT_DOMAIN}/api/v2/

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OATUH2_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${OATUH2_AUDIENCE}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL}
